version: "3"
services:

    client:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/client:latest
        restart: always
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/management:latest
        restart: always
        ports:
            - 5001:4000
        networks:
            - backend
        depends_on:
            - statistics-service-db

    statistics-service-api:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/statistics_service_api:latest
        restart: always
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics-service-worker:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/statistics_service_worker:latest
        restart: always
        networks:
            - frontend
            - backend

    statistics-service-redis:
        image: docker.pkg.github.com/idcf-boat-house/boat-house/redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics-service-db:
        image: docker.pkg.github.com/idcf-boat-house/boat-house/postgres:9.4
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend

    product-service-api:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/product_service_api:latest
        restart: always
        ports:
            - 7001:8080
        networks:
            - frontend
            - backend

    account-service-api:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/account_service_api:latest
        restart: always
        ports:
            - 7002:8080
        networks:
            - frontend
            - backend

    product-service-db:
        image: docker.pkg.github.com/idcf-boat-house/boat-house/mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./product-service/api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: P2ssw0rd
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data:
