version: "3"
services:

    client:
        build: ./client/web
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        build: ./management/web
        ports:
            - 5001:4000
        networks:
            - backend
        depends_on:
            - statistics-service-db

    statistics-service-api:
        build: ./statistics-service/api
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics_service_worker:
        build: ./statistics-service/worker
        networks:
            - frontend
            - backend

    statistics-service-redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics-service-db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend

    product-service-api:
        build: ./product-service/api
        ports:
            - 7001:8080
        networks:
            - frontend
            - backend

    product-service-db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./product-service/api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: P2ssw0rd
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data:
