version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
  # firefox:
  #   image: selenium/node-firefox:3.141.59-bismuth
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444