apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-worker-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: statistics-service-worker
  template:
    metadata:
      labels:
        app: statistics-service-worker
    spec:
      containers:
      - image: icdps.azurecr.io/statistics_service_worker:latest
        name: worker
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
